# Generated by Django 6.1 on 2026-08-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_customer_product_alter_journalentry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
