# Generated by Django 6.1 on 2026-08-16 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_invoice_subtotal_alter_invoice_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_en', models.CharField(default='SECOND ADVANCE MEDICAL COMPANY', max_length=255)),
                ('company_name_ar', models.CharField(default='الشركة الطبية المتقدمة الثانية', max_length=255)),
                ('vat_number', models.CharField(default='310122456700003', help_text='Saudi 15-Digit VAT ID', max_length=50)),
                ('cr_number', models.CharField(default='1010445566', help_text='Commercial Registration No', max_length=50)),
                ('address_en', models.TextField(default='Riyadh Industrial City, Saudi Arabia')),
                ('address_ar', models.TextField(default='المنطقة الصناعية، الرياض، المملكة العربية السعودية')),
                ('phone', models.CharField(default='+966 11 000 0000', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='name_ar',
            field=models.CharField(blank=True, help_text='الاسم بالعربية', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='Tax Invoice (فاتورة ضريبية)', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='zatca_qr_b64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(blank=True, help_text='اسم الصنف', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Customer VAT ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CONVERTED', 'Converted to Invoice'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.customer')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.quotation')),
            ],
        ),
    ]
