# Generated by Django 6.1 on 2026-08-17 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_companysettings_customer_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, help_text='اسم المورد', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='Supplier VAT ID (15 Digits)', max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.purchasebill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.supplier'),
        ),
    ]
