# Generated by Django 6.1 on 2026-08-17 19:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_purchasebill_supplier_purchasebillitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='vat_number',
            field=models.CharField(blank=True, help_text='Supplier VAT ID', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Al Rajhi Bank, Petty Cash (الخزينة)', max_length=150)),
                ('account_number', models.CharField(blank=True, help_text='IBAN or Account No', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('chart_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_records', to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(default='PV-001', max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash (نقدي)'), ('Bank Transfer', 'Bank Transfer (تحويل بنكي)'), ('Card', 'Card (بطاقة)'), ('Cheque', 'Cheque (شيك)')], default='Bank Transfer', max_length=50)),
                ('expense_reason', models.CharField(blank=True, help_text='e.g. Supplier Bill Settlement, Factory Rent, Fuel', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(help_text='Paid from Bank / Cash Drawer', on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount')),
                ('purchase_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.purchasebill')),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier if paying vendor bill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(default='RV-001', max_length=100, unique=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash (نقدي)'), ('Bank Transfer', 'Bank Transfer (تحويل بنكي)'), ('Mada / Card', 'Mada / Card (شبكة)'), ('Cheque', 'Cheque (شيك)')], default='Bank Transfer', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(help_text='Deposit to Bank / Cash Drawer', on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional linked invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.invoice')),
            ],
        ),
    ]
