# Generated by Django 6.1 on 2026-08-17 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_stocktransfer_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / General Manager (المدير العام)'), ('ACCOUNTANT', 'Accountant (المحاسب)'), ('SALESMAN', 'Salesman (مندوب مبيعات)'), ('WAREHOUSE_KEEPER', 'Warehouse Keeper (أمين المستودع)')], default='ADMIN', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_warehouse', models.ForeignKey(blank=True, help_text='Designated Division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.warehouse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
