# Generated by Django 6.1 on 2026-08-18 20:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_stocktransfer_notes_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('FINISHED_GOOD', 'Finished Good (منتج نهائي)'), ('RAW_MATERIAL', 'Raw Material (مادة خام)'), ('PACKAGING', 'Packaging Material (مواد تعبئة)')], default='FINISHED_GOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.warehouse'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='assigned_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.warehouse'),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_code', models.CharField(default='BOM-001', max_length=100, unique=True)),
                ('output_qty', models.IntegerField(default=1, help_text='Standard Batch Yield (e.g. 1000 Pcs)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('finished_product', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED_GOOD'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, help_text='Qty in Kg/Liters/Pcs per batch', max_digits=10)),
                ('scrap_allowance_pct', models.DecimalField(decimal_places=2, default=0.0, help_text='Expected wastage %', max_digits=5)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounting.billofmaterials')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_boms', to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default='WO-001', max_length=100, unique=True)),
                ('planned_qty', models.IntegerField(default=1000)),
                ('actual_qty_produced', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (مسودة)'), ('IN_PROGRESS', 'In Production (قيد التشغيل)'), ('QC_PENDING', 'QC Inspection (فحص الجودة)'), ('COMPLETED', 'Completed 🟢 (تم الإنتاج)'), ('CANCELLED', 'Cancelled 🔴')], default='DRAFT', max_length=30)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('machine_overhead', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_batch_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.billofmaterials')),
                ('warehouse', models.ForeignKey(help_text='Manufacturing Factory Division', on_delete=django.db.models.deletion.PROTECT, to='accounting.warehouse')),
            ],
        ),
    ]
