# Generated by Django 6.1 on 2026-08-19 09:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_product_cost_price_product_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company Name (English / Arabic)', max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='Saudi 15-Digit VAT ID', max_length=50, null=True)),
                ('cr_number', models.CharField(blank=True, help_text='Commercial Registration No', max_length=50, null=True)),
                ('address', models.TextField(default='Saudi Arabia')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly (شهري)'), ('YEARLY', 'Yearly (سنوي)')], default='MONTHLY', max_length=20)),
                ('status', models.CharField(choices=[('TRIAL', '14-Day Free Trial (تجربة مجانية)'), ('ACTIVE', 'Active Paid 🟢 (نشط)'), ('EXPIRED', 'Expired 🔴 (منتهي)'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=20)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateField(default=datetime.datetime.now)),
                ('auto_renew', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounting.company')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('amount_sar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Mada', 'Mada (مدى)'), ('Apple Pay', 'Apple Pay (أبل باي)'), ('Visa/Mastercard', 'Visa / Mastercard (بطاقة ائتمانية)'), ('Bank Transfer', 'Bank Wire (تحويل بنكي)')], default='Mada', max_length=50)),
                ('status', models.CharField(choices=[('PAID', 'Successful 🟢'), ('FAILED', 'Failed 🔴'), ('PENDING', 'Pending 🟡')], default='PAID', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.company')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Basic, Pro, Enterprise (باقة الأعمال)', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price_monthly_sar', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('price_yearly_sar', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('max_users', models.IntegerField(default=5)),
                ('max_invoices_per_month', models.IntegerField(default=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_warehouse',
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='bom_code',
            field=models.CharField(default='BOM-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='accounting.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='output_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='scrap_allowance_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='voucher_no',
            field=models.CharField(default='PV-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='bill_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quote_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='voucher_no',
            field=models.CharField(default='RV-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='transfer_no',
            field=models.CharField(default='TR-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_no',
            field=models.CharField(default='WO-001', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.warehouse'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_vouchers', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounting.company'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='accounting.company'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'cat_no')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'code')},
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.subscriptionplan'),
        ),
    ]
