# Generated by Django 6.1 on 2026-08-19 10:51

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_company_companysubscription_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_en', models.CharField(default='SECOND ADVANCE MEDICAL COMPANY', max_length=255)),
                ('company_name_ar', models.CharField(default='الشركة الطبية المتقدمة الثانية', max_length=255)),
                ('vat_number', models.CharField(default='310122456700003', max_length=50)),
                ('cr_number', models.CharField(default='1010445566', max_length=50)),
                ('address_en', models.TextField(default='Riyadh Industrial City, Saudi Arabia')),
                ('address_ar', models.TextField(default='المنطقة الصناعية، الرياض، المملكة العربية السعودية')),
                ('phone', models.CharField(default='+966 11 000 0000', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='companysubscription',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='companysubscription',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_invoices_per_month',
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset (الأصول)'), ('Liability', 'Liability (الخصوم)'), ('Equity', 'Equity (حقوق الملكية)'), ('Revenue', 'Revenue (الإيرادات)'), ('Expense', 'Expense (المصروفات)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(default='Riyadh Industrial City, Saudi Arabia'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cr_number',
            field=models.CharField(default='1010445566', help_text='Commercial Registration No', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name (English)', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, help_text='اسم الشركة بالعربية', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='+966 11 000 0000', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(default='310122456700003', help_text='Saudi 15-Digit VAT ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='Mada', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(default='PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('FINISHED_GOOD', 'Finished Good (منتج نهائي)'), ('RAW_MATERIAL', 'Raw Material (مادة خام)'), ('PACKAGING', 'Packaging Material (مواد تعبئة)'), ('SERVICE', 'Service (خدمة)')], default='FINISHED_GOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='payment_method',
            field=models.CharField(default='Bank Transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name_ar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=150)),
                ('name_ar', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='accounting.company')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_no', models.CharField(default='CN-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='accounting.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(default='EMP-001', max_length=50)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('iqama_no', models.CharField(help_text='Saudi National ID / Iqama', max_length=50)),
                ('iqama_expiry', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(default='Saudi', max_length=100)),
                ('bank_iban', models.CharField(help_text='Saudi IBAN', max_length=50)),
                ('bank_name', models.CharField(default='Al Rajhi Bank', max_length=100)),
                ('joining_date', models.DateField(default=datetime.datetime.now)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('other_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounting.company')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(default='AST-001', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField(default=datetime.datetime.now)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('depreciation_rate_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='accounting.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=20)),
                ('processed_date', models.DateField(default=datetime.datetime.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='accounting.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.monthlypayroll')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default='PO-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='ISSUED', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='accounting.company')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(default='SO-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='CONFIRMED', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='accounting.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_no', models.CharField(default='ADJ-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('system_qty', models.IntegerField()),
                ('physical_qty', models.IntegerField()),
                ('variance_qty', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='accounting.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.warehouse')),
            ],
        ),
    ]
