# Generated by Django 6.1 on 2026-08-19 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_companysettings_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='amount_refunded',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='zatca_qr_b64',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid (غير مدفوع) 🔴'), ('PARTIALLY_PAID', 'Partially Paid (مدفوع جزئياً) 🟡'), ('PAID', 'Paid (مدفوع) 🟢')], default='UNPAID', max_length=30),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid (غير مدفوع) 🔴'), ('PARTIALLY_PAID', 'Partially Paid (مدفوع جزئياً) 🟡'), ('PAID', 'Paid (مدفوع) 🟢')], default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='accounting.invoice'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(default='Goods Returned by Customer (مرتجع بضاعة)', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='purchase_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.purchasebill'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='accounting.invoice'),
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.creditnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
            ],
        ),
    ]
