# Generated by Django 6.1 on 2026-08-19 15:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_remove_creditnote_amount_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch_no',
            field=models.CharField(blank=True, help_text='Batch Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebillitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_no', models.CharField(default='DN-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('driver_name', models.CharField(blank=True, help_text='اسم السائق', max_length=150, null=True)),
                ('vehicle_no', models.CharField(blank=True, help_text='رقم اللوحة', max_length=50, null=True)),
                ('status', models.CharField(default='DELIVERED', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='accounting.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounting.invoice')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty_delivered', models.IntegerField(default=1)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(help_text='Batch / Lot Number', max_length=100)),
                ('manufacturing_date', models.DateField(default=datetime.datetime.now)),
                ('expiry_date', models.DateField(help_text='SFDA Expiry Date')),
                ('stock_qty', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accounting.product')),
            ],
        ),
    ]
