# Generated by Django 6.1 on 2026-08-19 15:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_invoiceitem_batch_no_invoiceitem_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='notes',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='driver_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_reconciled', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='accounting.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(default='DEBIT', max_length=20)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(default='FT-001', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfers', to='accounting.company')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.bankaccount')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.bankaccount')),
            ],
        ),
    ]
