# Generated by Django 6.1 on 2026-08-19 15:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_deliverynote_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_note_no', models.CharField(default='DN-001', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Goods Returned to Vendor (مرتجع مشتريات للمورد)', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='accounting.company')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='accounting.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.debitnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='DirectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_no', models.CharField(default='EXP-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(help_text='e.g. Office Rent, Factory Electricity, Fuel', max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(default='Bank Transfer', max_length=50)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_expenses', to='accounting.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('expense_account', models.ForeignKey(limit_choices_to={'account_type': 'Expense'}, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(default='GRN-001', max_length=100)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('received_by', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='accounting.company')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounting.purchasebill')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qty_received', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.goodsreceiptnote')),
            ],
        ),
    ]
