# Generated by Django 6.1 on 2026-08-19 16:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_debitnote_debitnoteitem_directexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='notes',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='cr_number',
            field=models.CharField(default='1010445566', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(default='310122456700003', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(default='Goods Returned by Customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='reason',
            field=models.CharField(default='Goods Returned to Vendor', max_length=255),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_iban',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='iqama_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid 🔴'), ('PARTIALLY_PAID', 'Partially Paid 🟡'), ('PAID', 'Paid 🟢')], default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('FINISHED_GOOD', 'Finished Good'), ('RAW_MATERIAL', 'Raw Material'), ('PACKAGING', 'Packaging'), ('SERVICE', 'Service')], default='FINISHED_GOOD', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid 🔴'), ('PARTIALLY_PAID', 'Partially Paid 🟡'), ('PAID', 'Paid 🟢')], default='UNPAID', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / General Manager'), ('ACCOUNTANT', 'Accountant'), ('SALESMAN', 'Salesman'), ('WAREHOUSE_KEEPER', 'Warehouse Keeper')], default='ADMIN', max_length=30),
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='accounting.company')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounting.pricelist'),
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(default='MONTHLY', max_length=20)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('next_issue_date', models.DateField(default=datetime.datetime.now)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='accounting.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.product')),
                ('recurring_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.recurringinvoice')),
            ],
        ),
    ]
