# Generated by Django 6.1 on 2026-08-19 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_goodsreceiptnote_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('FINISHED_GOOD', 'Finished Good (منتج نهائي)'), ('RAW_MATERIAL', 'Raw Material (مادة خام)'), ('BUNDLE', 'Product Bundle / Kit (منتج مجمع)'), ('SERVICE', 'Service (خدمة)')], default='FINISHED_GOOD', max_length=30),
        ),
        migrations.CreateModel(
            name='ProductBundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='accounting.product')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_bundles', to='accounting.product')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Piece, Box, Carton, Dozen', max_length=50)),
                ('symbol', models.CharField(help_text='e.g. Pcs, Ctn, Dz', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='accounting.company')),
            ],
        ),
    ]
