# Generated by Django 6.1 on 2026-08-21 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_customer_cr_number_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cat_no', models.CharField(default='', max_length=100)),
                ('item_name', models.CharField(default='', max_length=255)),
                ('lot_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('unit', models.CharField(default='Pcs', max_length=50)),
                ('reason', models.TextField(default='')),
                ('permission_by', models.CharField(default='QA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransferSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_no', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('target_division', models.CharField(default='Media', max_length=100)),
                ('cat_no', models.CharField(default='', max_length=100)),
                ('item_name', models.CharField(default='', max_length=255)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('status', models.CharField(default='TRANSFERRED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('bill_type', models.CharField(default='Petrol', max_length=50)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_litres', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('finger_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('iqama_no', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('iqama_exp', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(default='Bangladeshi', max_length=100)),
                ('org_type', models.CharField(default='Company Personnel', max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fundtransfer',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='fundtransfer',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bankstatementline',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='company',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='finished_product',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='bom',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='bom',
        ),
        migrations.RemoveField(
            model_name='bomitem',
            name='raw_material',
        ),
        migrations.RemoveField(
            model_name='unitofmeasure',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='monthlypayroll',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysubscription',
            name='company',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='company',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fundtransfer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='company',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='cost_center',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='credit_note',
        ),
        migrations.RemoveField(
            model_name='creditnoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='purchase_bill',
        ),
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='debit_note',
        ),
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='purchase_bill',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentryline',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='payroll',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='purchase_bill',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='pricelistitem',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='pricelistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productbundleitem',
            name='bundle_product',
        ),
        migrations.RemoveField(
            model_name='productbundleitem',
            name='component_product',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='purchasebillitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='recurringinvoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recurringinvoiceitem',
            name='recurring_invoice',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='source_warehouse',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='stocktransferitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Company Setting', 'verbose_name_plural': 'Company Settings'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='price_list',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='delivery_no',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='status',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='vehicle_no',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='expense_no',
        ),
        migrations.RemoveField(
            model_name='directexpense',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='supply_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='zatca_qr_b64',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='bill_no',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quote_no',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='next_issue_date',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='recurringinvoice',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cr_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name_ar',
        ),
        migrations.AddField(
            model_name='account',
            name='account_code',
            field=models.CharField(blank=True, default='1000', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='address',
            field=models.TextField(default='Riyadh, Kingdom of Saudi Arabia'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='email',
            field=models.EmailField(default='info@samco.sa', max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='gate_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='ref_po',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='expense_category',
            field=models.CharField(default='General Expense', max_length=100),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='directexpense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='PAID', max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='currency',
            field=models.CharField(default='SAR', max_length=10),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Warehouse', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Pcs', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='bill_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(default='PAID', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='next_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recurringinvoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(default='Asset', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='General Account', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name_ar',
            field=models.CharField(default='شركة التقدم الطبي الثانية', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name_en',
            field=models.CharField(default='SECOND ADVANCE MEDICAL COMPANY (SAMCO)', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(default='300000000000003', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='directexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(default='Tax Invoice', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(default='General Entry'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat_no',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.supplier'),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.customer'),
        ),
        migrations.AlterField(
            model_name='recurringinvoice',
            name='frequency',
            field=models.CharField(default='Monthly', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='Supplier', max_length=255),
        ),
        migrations.CreateModel(
            name='SalarySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='', max_length=50)),
                ('present_days', models.IntegerField(default=30)),
                ('base_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(default='PAID 🟢', max_length=50)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.worker')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.CharField(default='08:00:00', max_length=50)),
                ('check_out', models.CharField(default='17:00:00', max_length=50)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('status', models.CharField(default='Present', max_length=50)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='BankStatement',
        ),
        migrations.DeleteModel(
            name='BankStatementLine',
        ),
        migrations.DeleteModel(
            name='BillOfMaterials',
        ),
        migrations.DeleteModel(
            name='BOMItem',
        ),
        migrations.DeleteModel(
            name='UnitOfMeasure',
        ),
        migrations.DeleteModel(
            name='PaymentTransaction',
        ),
        migrations.DeleteModel(
            name='FundTransfer',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanySubscription',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='FixedAsset',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
        migrations.DeleteModel(
            name='CreditNote',
        ),
        migrations.DeleteModel(
            name='CreditNoteItem',
        ),
        migrations.DeleteModel(
            name='DebitNote',
        ),
        migrations.DeleteModel(
            name='DebitNoteItem',
        ),
        migrations.DeleteModel(
            name='DeliveryNoteItem',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptItem',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptNote',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
        migrations.DeleteModel(
            name='MonthlyPayroll',
        ),
        migrations.DeleteModel(
            name='PayrollItem',
        ),
        migrations.DeleteModel(
            name='PaymentVoucher',
        ),
        migrations.DeleteModel(
            name='PriceListItem',
        ),
        migrations.DeleteModel(
            name='ProductBatch',
        ),
        migrations.DeleteModel(
            name='ProductBundleItem',
        ),
        migrations.DeleteModel(
            name='PurchaseBillItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucher',
        ),
        migrations.DeleteModel(
            name='RecurringInvoiceItem',
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
        migrations.DeleteModel(
            name='StockAdjustment',
        ),
        migrations.DeleteModel(
            name='StockTransfer',
        ),
        migrations.DeleteModel(
            name='StockTransferItem',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='WarehouseStock',
        ),
    ]
