# Generated by Django 6.1 on 2026-08-21 22:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_rejectlog_transferslip_vehiclebill_worker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('Warehouse', 'Warehouse Division'), ('Media', 'Media Division'), ('Plastic', 'Plastic Division'), ('Cosmetic', 'Cosmetic Division'), ('Powder', 'Powder Division'), ('Super Admin', 'Super Admin Suite')], default='Warehouse', max_length=50)),
                ('username', models.CharField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail / Email')),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contract / Contact Number')),
                ('image', models.FileField(blank=True, null=True, upload_to='division_users/', verbose_name='PNG Image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Division Manager / User',
                'verbose_name_plural': 'Division Managers / Users',
            },
        ),
    ]
